#!/usr/bin/env bash
set -e
NAMES="debian ubuntu rocky"
TPL="./test.yaml.tpl"
for NAME in $NAMES;do
    OUT="Test-${NAME}.yaml"
    {
        echo "##"
        echo "## This file was generated by $0 from template $TPL"
        echo "## Do not edit. Edit the template instead."
        echo "##"
    }>"${OUT}"
    sed s/%NAME/"$NAME"/g < ${TPL} >> "${OUT}"
done
